### ISSUE TITLE
Download videos fails when testing on parseJSON

### ISSUE THREAD

**Issue by x0s** [blenzi/VideoSplitter#9]
I'm trying to reproduce the tests but it is failing at download.

Here is my log:
```
$ git checkout parseJSON
$ python -m unittest -v test/test_parseAnnotations.py
``` 

yields

```
Downloading 13.96 MB
ERROR
test_pickFrames (test.test_parseAnnotations.TestFunctions) ... ok
test_splitStates1 (test.test_parseAnnotations.TestFunctions)
Split states with start and endpoints ... ok
test_splitStates2 (test.test_parseAnnotations.TestFunctions)
Split states without endpoint ... ok

======================================================================
ERROR: setUpClass (test.test_parseAnnotations.TestAnnotationParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/.../VideoSplitter/test/test_parseAnnotations.py", line 97, in setUpClass
    setupTester(cls)
  File "/.../VideoSplitter/test/test_parseAnnotations.py", line 83, in setupTester
    stream.download(cls.inputdir / dest)
  File "/.../lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 181, in download
    downloader.download(filepath, infodict)
  File "/.../lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 342, in download
    and os.path.isfile(encodeFilename(filename))
  File "/.../lib/python3.6/site-packages/youtube_dl/utils.py", line 2223, in encodeFilename
    assert type(s) == compat_str
AssertionError

----------------------------------------------------------------------
Ran 3 tests in 1.926s

FAILED (errors=1)
```

Any idea why this is crashing ?
Thanks

**Comment by blenzi** [comment]
Hi @x0s ,

I could not reproduce the issue. The videos were downloaded properly and the test succeeded. Extracts of the log below:

```
Downloading 13.96 MB
Downloading 14.75 MB100.00%] received. Rate: [4096 KB/s].  ETA: [0 secs]
...
Ran 9 tests in 16.682s
```

**Comment by x0s** [comment]
If I clone again, I still have the same issue
```shell
git clone https://github.com/blenzi/VideoSplitter.git
cd VideoSplitter/
git checkout parseJSON
touch test/__init__.py
python -m unittest -v test/test_parseAnnotations.py
```

**Comment by x0s** [comment]
I have investigated, I found that the backend of youtube-dl that is used by pafy to download **does not accept**  (python 3.4+)`Path` object

**Comment by x0s** [comment]
I have investigated, I found that the backend of youtube-dl that is used by pafy to download **does not accept**  (python 3.4+) `Path` object

[Here](https://github.com/blenzi/VideoSplitter/blob/parseJSON/test/test_parseAnnotations.py#L83), a Path object is passed to the downloader.
But the downloader does not accept Path object: see [here](https://github.com/ytdl-org/youtube-dl/blob/1a01639bf9514c20d54e7460ba9b493b3283ca9a/youtube_dl/utils.py#L635) and [here](https://github.com/ytdl-org/youtube-dl/blob/1a01639bf9514c20d54e7460ba9b493b3283ca9a/youtube_dl/compat.py#L2355)

Unfortunately, the assertion is vacuous, that's why the incompatibility was not clear. Indeed:
```python
from pathlib import Path
isinstance(type(Path()), str) # False
```

So, I don't understand how you succeeded in downloading the videos.
A solution is to return a string

**Comment by x0s** [comment]
#12 fixes this issue. Now closing!
